### ISSUE TITLE
User not a sudoer

### ISSUE THREAD

**Issue by bjornborg** [chalmers-revere/opendlv.os#1] opened 2016-12-08 10:00 UTC
The created user is not automatically a sudoer:
- reverian is not in the sudoers file.  This incident will be reported.
Moreover, it causes problems for some installation steps where root privileges are required.

**Comment by olbender** [comment] 2016-12-13 23:11
This is the intended behaviour. We do not want the normal user to get any root privileges. @chrberger is this a valid default setting? If we would like to change this, I will add a new "setup-user-sudo.sh" to only include this on demand (not by default).

**Comment by chrberger** [comment] 2016-12-14 09:23
@olbender I think it would be good to minimize the allowed permissions; so, I vote for that the normal user is not sudo-able.

**Comment by olbender** [comment] 2016-12-14 10:20
Great, then we close this issue without any change.

**Closed as completed by olbender** 2016-12-14 10:20 UTC
