### ISSUE TITLE
"$ pip install docker-compose" not working

### ISSUE THREAD

**Issue by Adam2092** [chalmers-revere/opendlv.os#51] opened 2019-04-16 08:08 UTC
I tried installing the python-related packages required by the error message; still not working afterwards because of errors in the script used by pip.

FYI: Instead I manually ran `$ apt install docker-compose` with root privilege and it worked.

**Comment by chrberger** [comment] 2019-04-16 08:10
What error message are you referring to?

**Comment by Adam2092** [comment] 2019-04-16 08:12
The terminal was cleared... I will report with a screenshot when I re-flash the OS of the next BBBlue board.

**Comment by Adam2092** [comment] 2019-04-17 12:33
Here are the screenshots of error messages:

![001](https://user-images.githubusercontent.com/3759112/56287703-64869c00-611d-11e9-9d1f-123738db424c.png)

I installed then the package of cffi: `$apt install python-cffi python-cffi-backend -y`
Afterwards the pip install process exited with the following error:

![002](https://user-images.githubusercontent.com/3759112/56287714-69e3e680-611d-11e9-98f5-a7ce59bc4060.png)

**Comment by chrberger** [comment] 2019-04-18 17:26
The issue is still unclear to me; what are you trying to achieve?

**Comment by Adam2092** [comment] 2019-04-18 17:37
I was trying to re-install the debian OS as well as the necessary packages/dependencies on BB Blue boards using [the script install.sh](https://github.com/chalmers-revere/opendlv.os/blob/kiwi/kiwi/arm-bbblue/install.sh), which would yield the error above at line 116 `$ pip install docker-compose`  (I should have directly pointed to the file earlier, or even more precisely this line).

This issue didn't exist previously when I did the re-installing for the first cars 3 weeks ago; the script hasn't been modified since then.

**Comment by bjornborg** [comment] 2020-03-16 16:12
This is now fixed with ```apt``` command instead

**Closed as completed by bjornborg** 2020-03-16 16:12 UTC
